apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: nestjs
        image: localhost:5000/ims:latest
        ports:
        - containerPort: 9000
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "ims"
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_SYNCHRONIZE
          value: "true"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: BREVO_SMTP
          value: "smtp-relay.brevo.com"
        - name: BREVO_SMTP_PORT
          value: "587"
        - name: BREVO_USER
          value: "leogavin123@gmail.com"
        - name: BREVO_PASS
          valueFrom:
            secretKeyRef:
              name: brevo-secret
              key: password
        - name: EMAIL_FROM_ADDRESS
          value: "ims@noreply.com"
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
